// Company Data Model - lastUpdated: 2026-03-26
const COMPANY_DB = {
  'cathay-life': { name: '國泰人壽', short: '國泰', type: 'life', contract: '雙合約制', benefits: '有勞健保', marketShare: '21.3%',
    defaults: { insurance: { commRate: 20, renewalRate: 3, renewalDecay: 0.6, orgAllowance: 0 }, banker: { bankComm: 8, fixedSalary: 800000 }, manager: { personalComm: 22, orgAllowance: 800000, personalRenewal: 200000 }, medical: { currentComm: 15 }, newbie: { altComm: 18 } },
    comparison: { productChoice: '限自家產品', ceiling: '受職階與公司政策限制', training: '完整培訓體系', brand: '大型品牌光環' },
    note: '雙合約制（承攬+僱傭），提供勞健保、勞退、團險' },
  'fubon-life': { name: '富邦人壽', short: '富邦', type: 'life', contract: '雙合約制', benefits: '有勞健保', marketShare: '14.8%',
    defaults: { insurance: { commRate: 20, renewalRate: 3, renewalDecay: 0.6, orgAllowance: 0 }, banker: { bankComm: 8, fixedSalary: 850000 }, manager: { personalComm: 21, orgAllowance: 900000, personalRenewal: 200000 }, medical: { currentComm: 15 }, newbie: { altComm: 18 } },
    comparison: { productChoice: '限自家產品', ceiling: '受職階與公司政策限制', training: '完整培訓體系', brand: '金融集團整合優勢' },
    note: '金控體系，銀行保險通路強' },
  'nanshan-life': { name: '南山人壽', short: '南山', type: 'life', contract: '純承攬制', benefits: '自行投保', marketShare: '12.4%',
    defaults: { insurance: { commRate: 25, renewalRate: 4, renewalDecay: 0.65, orgAllowance: 0 }, banker: { bankComm: 0, fixedSalary: 0 }, manager: { personalComm: 25, orgAllowance: 600000, personalRenewal: 250000 }, medical: { currentComm: 18 }, newbie: { altComm: 22 } },
    comparison: { productChoice: '限自家產品', ceiling: '受組織架構限制', training: '完整培訓體系', brand: '老牌聲譽' },
    note: '純承攬制，佣金率較高但無勞健保' },
  'shin-kong-life': { name: '新光人壽', short: '新光', type: 'life', contract: '雙合約制', benefits: '有勞健保', marketShare: '7.7%',
    defaults: { insurance: { commRate: 19, renewalRate: 2.5, renewalDecay: 0.55, orgAllowance: 0 }, banker: { bankComm: 7, fixedSalary: 750000 }, manager: { personalComm: 20, orgAllowance: 700000, personalRenewal: 180000 }, medical: { currentComm: 14 }, newbie: { altComm: 17 } },
    comparison: { productChoice: '限自家產品', ceiling: '受職階與公司政策限制', training: '完整培訓體系', brand: '老牌品牌' },
    note: '雙合約制，新人財務補助計畫' },
  'yongda': { name: '永達保經', short: '永達', type: 'broker', contract: '承攬制', benefits: '自行投保', marketShare: '保經前三',
    defaults: { insurance: { commRate: 22, renewalRate: 3, renewalDecay: 0.6, orgAllowance: 0 }, manager: { personalComm: 22, orgAllowance: 0, personalRenewal: 0 }, newbie: { altComm: 22 } },
    brokerDefaults: { brokerComm: 38, renewalRate: 4.5, orgRate: 3 },
    comparison: { productChoice: '多家保司產品', ceiling: '依個人能力', training: '自主學習為主', brand: '上市公司、兩岸布局' },
    note: '增員獎 2.4 萬/人，晉級獎最高 310 萬' },
  'leishan': { name: '磊山保經', short: '磊山', type: 'broker', contract: '承攬制', benefits: '自行投保', marketShare: '快速成長',
    defaults: { insurance: { commRate: 22, renewalRate: 3, renewalDecay: 0.6, orgAllowance: 0 }, manager: { personalComm: 22, orgAllowance: 0, personalRenewal: 0 }, newbie: { altComm: 22 } },
    brokerDefaults: { brokerComm: 38, renewalRate: 4.5, orgRate: 3 },
    comparison: { productChoice: '多家保司產品', ceiling: '依個人能力', training: '內部培訓完善', brand: '2024年保費80億、YoY+86%' },
    note: '2025年目標保費120億、人力2000人' },
  'dinglv': { name: '錠嵂保經', short: '錠嵂', type: 'broker', contract: '承攬制', benefits: '自行投保', marketShare: '知名品牌',
    defaults: { insurance: { commRate: 20, renewalRate: 3, renewalDecay: 0.6, orgAllowance: 0 }, manager: { personalComm: 20, orgAllowance: 0, personalRenewal: 0 }, newbie: { altComm: 20 } },
    brokerDefaults: { brokerComm: 36, renewalRate: 4, orgRate: 2.5 },
    comparison: { productChoice: '多家保司產品', ceiling: '依個人能力', training: '網路口碑佳', brand: '網路聲量高' }, note: '' },
  'dacheng': { name: '大誠保經', short: '大誠', type: 'broker', contract: '承攬制', benefits: '自行投保', marketShare: '卓越評比',
    defaults: { insurance: { commRate: 20, renewalRate: 3, renewalDecay: 0.6, orgAllowance: 0 }, manager: { personalComm: 20, orgAllowance: 0, personalRenewal: 0 }, newbie: { altComm: 20 } },
    brokerDefaults: { brokerComm: 36, renewalRate: 4, orgRate: 2.5 },
    comparison: { productChoice: '多家保司產品', ceiling: '依個人能力', training: '企業通路強', brand: '卓越保險評比得獎' }, note: '' },
  'other-broker': { name: '其他保經', short: '其他', type: 'broker', contract: '承攬制', benefits: '自行投保', marketShare: '—',
    defaults: { insurance: { commRate: 20, renewalRate: 3, renewalDecay: 0.6, orgAllowance: 0 }, manager: { personalComm: 20, orgAllowance: 0, personalRenewal: 0 }, newbie: { altComm: 20 } },
    brokerDefaults: { brokerComm: 35, renewalRate: 4, orgRate: 2 },
    comparison: { productChoice: '多家保司產品', ceiling: '依個人能力', training: '—', brand: '—' },
    note: '手動輸入實際數值' },
  'custom': { name: '自訂公司', short: '自訂', type: 'custom', contract: '—', benefits: '—', marketShare: '—',
    defaults: { insurance: { commRate: 20, renewalRate: 3, renewalDecay: 0.6, orgAllowance: 0 }, banker: { bankComm: 8, fixedSalary: 800000 }, manager: { personalComm: 22, orgAllowance: 800000, personalRenewal: 200000 }, medical: { currentComm: 15 }, newbie: { altComm: 18 } },
    comparison: { productChoice: '—', ceiling: '—', training: '—', brand: '—' },
    note: '所有欄位手動輸入' },
};
const GONGSHENG_COMPARE = { contract: '承攬制', benefits: '自行投保（職業工會）', productChoice: '多家保司產品', ceiling: '無上限', training: 'MDRT 系統培訓', brand: '連續七年保經業第一' };
